void err() {
  cout << ${1:出力} << endl;
  exit(0);
}
